name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:    

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PowerShell
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -MinimumVersion 5.4.1
        shell: pwsh

      - name: Create release notes
        id: create_release_notes
        run: |
          echo "## Release Notes" > release_notes.md
          echo "" >> release_notes.md
          echo "### Changes in this release:" >> release_notes.md
          echo "" >> release_notes.md
          git log --oneline $(git describe --tags --abbrev=0)..HEAD >> release_notes.md
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./release_notes.md
          draft: false
          prerelease: false

      - name: Upload PowerShell script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Switch-ReposVisibility.ps1
          asset_name: Switch-ReposVisibility.ps1
          asset_content_type: text/plain

      - name: Upload README.md
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./README.md
          asset_name: README.md
          asset_content_type: text/markdown