name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Get previous tag
        id: prev-tag
        run: echo "::set-output name=tag::$(git describe --tags $(git describe --tags --abbrev=0)^)"

      - name: Generate release notes
        id: release-notes
        run: |
          PREV_TAG=${{ steps.prev-tag.outputs.tag }}
          echo "Previous tag: $PREV_TAG"
          git log --oneline $PREV_TAG..HEAD > release_notes.md
        shell: bash

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release-notes.outputs.notes }}
          draft: false
          prerelease: false
